export const programsAcademic = [
    "Administración de Empresas",
    "Arquitectura",
    "Comercio Internacional",
    "Comunicación Social ",
    "Contaduría Pública",
    "Derecho",
    "Enfermería ",
    "Ingeniería Agroindustrial",
    "Ingeniería Agronómica ",
    "Ingeniería Ambiental ",
    "Ingeniería Biotecnológica ",
    "Ingeniería Civil",
    "Ingeniería de Minas",
    "Ingeniería de Sistemas ",
    "Ingeniería Electromecánica",
    "Ingeniería Electrónica ",
    "Ingeniería Industrial",
    "Ingeniería Mecánica",
    "Licenciatura en Matemáticas ",
    "Licenciatura en Ciencias Naturales y Educación Ambiental",
    "Licenciatura en Educación Infantil",
    "Química Industrial",
    "Seguridad y Salud en el Trabajo",
    "Trabajo Social",
    "Zootecnia"
]